# Generated by Django 2.2.1 on 2019-05-09 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='LASER', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Laser',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='title',
        ),
        migrations.RemoveField(
            model_name='silo',
            name='title',
        ),
        migrations.AddField(
            model_name='measurement',
            name='read',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='saved',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Silo'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='silo',
            name='capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='silo',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='silo',
            name='location',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='silo',
            name='width',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='silo',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sensor'),
        ),
    ]
