# Generated by Django 2.2.1 on 2019-05-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_silo_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='silo',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
