# Generated by Django 2.2.1 on 2019-11-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='acc',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='measurement',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pressure',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor_timestamp',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='measurement',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
