# Generated by Django 2.2.1 on 2019-12-23 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sensor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silo',
            name='sensor',
        ),
        migrations.AddField(
            model_name='sensor',
            name='silo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Silo'),
        ),
    ]
