# Generated by Django 2.2.1 on 2019-12-23 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20191223_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='user',
        ),
        migrations.AddField(
            model_name='silo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
