# Generated by Django 2.2.1 on 2020-01-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200113_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='content',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='radius',
            field=models.FloatField(default=0),
        ),
    ]
