# Generated by Django 2.2.1 on 2020-01-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200113_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
