# Generated by Django 2.2.1 on 2020-01-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200113_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='charge',
        ),
    ]
