# Generated by Django 2.2.1 on 2020-01-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_measurement_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='silo_gap_bottom',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='silo_gap_top',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='silo_height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='silo_width',
            field=models.FloatField(default=0),
        ),
    ]
